name: Docker Image CI

on:
  pull_request:
    types:
      - closed

  push:
    branches:
      - main

env:
  TEST_TAG: melonboy10/hermes-minecraft-server-manager:test
  LATEST_TAG: melonboy10/hermes-minecraft-server-manager:latest

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # - name: Build the Docker image
      #   uses: actions/checkout@v3
      #   run: docker build . --file Dockerfile --tag hermes-minecraft-server-manager:$(date +%s)
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.LATEST_TAG }}
          labels: ${{ env.LATEST_TAG }}
