name: Docker Image CI

on: [push]

env:
  TEST_TAG: melonboy10/hermes-minecraft-server-manager:test
  LATEST_TAG: melonboy10/hermes-minecraft-server-manager:latest

jobs:
  lint:
    name: Lint the code and check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # - name: Build the Docker image
      #   uses: actions/checkout@v3
      #   run: docker build . --file Dockerfile --tag hermes-minecraft-server-manager:$(date +%s)
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install pnpm -g && pnpm install --frozen-lockfile

      - name: Svelte Check
        run: pnpm run check

      - name: ESLint Check
        run: pnpm run lint

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: Test the Docker image
        run: |
          CONTAINER_ID=$(docker run -d --name hermes-mcsm ${{ env.TEST_TAG }})
          sleep 30
          echo $(docker container inspect -f '{{.State.Status}}' ${CONTAINER_ID})
          if [ "$( docker container inspect -f '{{.State.Status}}' ${CONTAINER_ID})" != "running" ]; then
            echo "Error: Docker container exited before 30 seconds"
            exit 1
          fi
          docker stop ${CONTAINER_ID}
          docker rm ${CONTAINER_ID}
          echo "Test passed"
